linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: itswork.app

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo
    - goimports
    - misspell
    - lll
    - gofmt

run:
  timeout: 5m
  tests: true

issues:
  exclude-dirs:
    - venv
    - web
