# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.proto import CONTRACTS_pb2 as CONTRACTS__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in CONTRACTS_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IntelligenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeToken = channel.unary_unary(
                '/itswork.intelligence.IntelligenceService/AnalyzeToken',
                request_serializer=CONTRACTS__pb2.TokenRequest.SerializeToString,
                response_deserializer=CONTRACTS__pb2.VerdictResponse.FromString,
                _registered_method=True)


class IntelligenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntelligenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeToken': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeToken,
                    request_deserializer=CONTRACTS__pb2.TokenRequest.FromString,
                    response_serializer=CONTRACTS__pb2.VerdictResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'itswork.intelligence.IntelligenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('itswork.intelligence.IntelligenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IntelligenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/itswork.intelligence.IntelligenceService/AnalyzeToken',
            CONTRACTS__pb2.TokenRequest.SerializeToString,
            CONTRACTS__pb2.VerdictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
