# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/proto/CONTRACTS.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api/proto/CONTRACTS.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61pi/proto/CONTRACTS.proto\x12\x14itswork.intelligence\"=\n\x0cTokenRequest\x12\x14\n\x0cmint_address\x18\x01 \x01(\t\x12\x17\n\x0f\x63reator_address\x18\x02 \x01(\t\"A\n\x0fVerdictResponse\x12\r\n\x05score\x18\x01 \x01(\x05\x12\x0f\n\x07verdict\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t2p\n\x13IntelligenceService\x12Y\n\x0c\x41nalyzeToken\x12\".itswork.intelligence.TokenRequest\x1a%.itswork.intelligence.VerdictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.proto.CONTRACTS_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOKENREQUEST']._serialized_start=51
  _globals['_TOKENREQUEST']._serialized_end=112
  _globals['_VERDICTRESPONSE']._serialized_start=114
  _globals['_VERDICTRESPONSE']._serialized_end=179
  _globals['_INTELLIGENCESERVICE']._serialized_start=181
  _globals['_INTELLIGENCESERVICE']._serialized_end=293
# @@protoc_insertion_point(module_scope)
