// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/CONTRACTS.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MintAddress    string                 `protobuf:"bytes,1,opt,name=mint_address,json=mintAddress,proto3" json:"mint_address,omitempty"`
	CreatorAddress string                 `protobuf:"bytes,2,opt,name=creator_address,json=creatorAddress,proto3" json:"creator_address,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_api_proto_CONTRACTS_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_CONTRACTS_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_CONTRACTS_proto_rawDescGZIP(), []int{0}
}

func (x *TokenRequest) GetMintAddress() string {
	if x != nil {
		return x.MintAddress
	}
	return ""
}

func (x *TokenRequest) GetCreatorAddress() string {
	if x != nil {
		return x.CreatorAddress
	}
	return ""
}

type VerdictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int32                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Verdict       string                 `protobuf:"bytes,2,opt,name=verdict,proto3" json:"verdict,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerdictResponse) Reset() {
	*x = VerdictResponse{}
	mi := &file_api_proto_CONTRACTS_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerdictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerdictResponse) ProtoMessage() {}

func (x *VerdictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_CONTRACTS_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerdictResponse.ProtoReflect.Descriptor instead.
func (*VerdictResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_CONTRACTS_proto_rawDescGZIP(), []int{1}
}

func (x *VerdictResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *VerdictResponse) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *VerdictResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_api_proto_CONTRACTS_proto protoreflect.FileDescriptor

const file_api_proto_CONTRACTS_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/CONTRACTS.proto\x12\x14itswork.intelligence\"Z\n" +
	"\fTokenRequest\x12!\n" +
	"\fmint_address\x18\x01 \x01(\tR\vmintAddress\x12'\n" +
	"\x0fcreator_address\x18\x02 \x01(\tR\x0ecreatorAddress\"Y\n" +
	"\x0fVerdictResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x05R\x05score\x12\x18\n" +
	"\averdict\x18\x02 \x01(\tR\averdict\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason2p\n" +
	"\x13IntelligenceService\x12Y\n" +
	"\fAnalyzeToken\x12\".itswork.intelligence.TokenRequest\x1a%.itswork.intelligence.VerdictResponseB\x17Z\x15itswork.app/api/protob\x06proto3"

var (
	file_api_proto_CONTRACTS_proto_rawDescOnce sync.Once
	file_api_proto_CONTRACTS_proto_rawDescData []byte
)

func file_api_proto_CONTRACTS_proto_rawDescGZIP() []byte {
	file_api_proto_CONTRACTS_proto_rawDescOnce.Do(func() {
		file_api_proto_CONTRACTS_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_CONTRACTS_proto_rawDesc), len(file_api_proto_CONTRACTS_proto_rawDesc)))
	})
	return file_api_proto_CONTRACTS_proto_rawDescData
}

var file_api_proto_CONTRACTS_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_CONTRACTS_proto_goTypes = []any{
	(*TokenRequest)(nil),    // 0: itswork.intelligence.TokenRequest
	(*VerdictResponse)(nil), // 1: itswork.intelligence.VerdictResponse
}
var file_api_proto_CONTRACTS_proto_depIdxs = []int32{
	0, // 0: itswork.intelligence.IntelligenceService.AnalyzeToken:input_type -> itswork.intelligence.TokenRequest
	1, // 1: itswork.intelligence.IntelligenceService.AnalyzeToken:output_type -> itswork.intelligence.VerdictResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_CONTRACTS_proto_init() }
func file_api_proto_CONTRACTS_proto_init() {
	if File_api_proto_CONTRACTS_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_CONTRACTS_proto_rawDesc), len(file_api_proto_CONTRACTS_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_CONTRACTS_proto_goTypes,
		DependencyIndexes: file_api_proto_CONTRACTS_proto_depIdxs,
		MessageInfos:      file_api_proto_CONTRACTS_proto_msgTypes,
	}.Build()
	File_api_proto_CONTRACTS_proto = out.File
	file_api_proto_CONTRACTS_proto_goTypes = nil
	file_api_proto_CONTRACTS_proto_depIdxs = nil
}
